name: Validate XMLTV
on: [push]
jobs:
  validate-xmltv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v .

      - name: Install xmltv
        run: sudo apt-get install -y xmltv

      - name: Run stirr-for-channels (national)
        run: ./stirr-for-channels &
        env:
          PORT: 8088
          STIRR_STATION_ID: national

      - name: Run stirr-for-channels (SF)
        run: ./stirr-for-channels &
        env:
          PORT: 8089
          STIRR_STATION_ID: san-francisco

      - name: Wait for stirr-for-channels to start
        run: sleep 60

      - name: Download national EPG
        run: curl -o national.xml http://localhost:8088/epg.xml

      - name: Download SF EPG
        run: curl -o sf.xml http://localhost:8089/epg.xml

      - name: Validate national EPG
        run: tv_validate_file national.xml

      - name: Validate SF EPG
        run: tv_validate_file sf.xml
